[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cp package-server.json package.json", "npm install --omit=dev"]

[phases.build]
cmds = ["mkdir -p dist && echo '{\"status\":\"api-server\"}' > dist/index.html"]

[start]
cmd = "node server.js"
