// PDF Export Service - Export health data and reports
import { jsPDF } from 'jspdf';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { Capacitor } from '@capacitor/core';

class PDFExportService {
  // Helper to save PDF on mobile devices
  async savePDFMobile(doc, filename) {
    try {
      if (Capacitor.isNativePlatform()) {
        // Get PDF as base64
        const pdfBase64 = doc.output('datauristring').split(',')[1];
        
        // Save to cache directory (temporary, shareable, no permissions needed)
        const result = await Filesystem.writeFile({
          path: filename,
          data: pdfBase64,
          directory: Directory.Cache
        });
        
        if(import.meta.env.DEV)console.log('✅ PDF saved to:', result.uri);
        
        // Share the PDF
        await Share.share({
          title: 'Helio Health Report',
          text: 'Your health report from Helio',
          url: result.uri,
          dialogTitle: 'Share your report'
        });
        
        alert('✅ PDF ready to share!');
      } else {
        // Browser - use normal download
        doc.save(filename);
      }
    } catch (error) {
      if(import.meta.env.DEV)console.error('❌ PDF save error:', error);
      alert('Failed to save PDF: ' + error.message);
    }
  }

  // Export daily stats summary WITH ALL DATA
  async exportDailyStats(stats) {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString();
    
    // Title
    doc.setFontSize(20);
    doc.text('Helio Daily Health Report', 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Date: ${today}`, 20, 30);
    
    // Stats
    doc.setFontSize(14);
    doc.text('Daily Activity Summary', 20, 45);
    
    doc.setFontSize(11);
    let y = 55;
    doc.text(`Steps: ${stats.todaySteps} / ${stats.goalSteps}`, 25, y);
    y += 8;
    doc.text(`Water: ${stats.waterCups} / 8 cups`, 25, y);
    y += 8;
    doc.text(`Meals Logged: ${stats.mealsLogged}`, 25, y);
    y += 8;
    doc.text(`Streak: ${stats.streak} days`, 25, y);
    y += 8;
    doc.text(`Level: ${stats.level} | XP: ${stats.xp}`, 25, y);
    y += 8;
    doc.text(`Wellness Score: ${stats.wellnessScore}/100`, 25, y);
    
    // Weekly Steps Chart
    y += 15;
    doc.setFontSize(14);
    doc.text('Weekly Steps Summary', 20, y);
    y += 10;
    doc.setFontSize(10);
    
    const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    stats.weeklySteps?.forEach((day, index) => {
      doc.text(`${days[index]}: ${day.steps || 0} steps`, 25, y);
      y += 7;
    });
    
    // NEW: Health Metrics Section
    y += 10;
    doc.setFontSize(14);
    doc.text('Health Metrics', 20, y);
    y += 10;
    doc.setFontSize(11);
    
    // Get sleep data
    try {
      const sleepLog = JSON.parse(localStorage.getItem('sleepLog') || '[]');
      const todaySleep = sleepLog.filter(s => {
        const sleepDate = new Date(s.date).toLocaleDateString();
        return sleepDate === today;
      })[0];
      doc.text(`Sleep Last Night: ${todaySleep?.hours || 'Not tracked'} hours`, 25, y);
    } catch (e) {
      doc.text(`Sleep Last Night: Not tracked`, 25, y);
    }
    y += 8;
    doc.text(`Heart Rate: ${stats.heartRate ? stats.heartRate + ' bpm' : 'Not monitored'}`, 25, y);
    y += 8;
    doc.text(`BMI: ${stats.bmi ? stats.bmi.toFixed(1) : 'Not calculated'}`, 25, y);
    y += 8;
    doc.text(`Stress Level: ${stats.stressLevel || 'Not tracked'}`, 25, y);
    
    // Footer
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 280);
    doc.text('This report is for informational purposes only', 20, 285);
    
    // Save with timestamp
    const timestamp = new Date().toISOString().split('T')[0];
    await this.savePDFMobile(doc, `helio-daily-stats-${timestamp}.pdf`);
  }

  // Export workout history
  async exportWorkoutHistory() {
    const doc = new jsPDF();
    const workoutLog = JSON.parse(localStorage.getItem('workoutHistory') || '[]');
    const today = new Date().toLocaleDateString();
    
    // Calculate workout metrics
    const totalWorkouts = workoutLog.length;
    const totalCalories = workoutLog.reduce((sum, w) => sum + (w.calories || 0), 0);
    const totalDuration = workoutLog.reduce((sum, w) => sum + (w.duration || 0), 0);
    const avgDuration = totalWorkouts > 0 ? (totalDuration / totalWorkouts).toFixed(1) : 0;
    
    // Get workout breakdown by type
    const workoutsByType = {};
    workoutLog.forEach(w => {
      const type = w.type || 'General';
      workoutsByType[type] = (workoutsByType[type] || 0) + 1;
    });
    
    // Calculate last 7 days stats
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    const last7Days = workoutLog.filter(w => new Date(w.date) >= sevenDaysAgo);
    const last7Calories = last7Days.reduce((sum, w) => sum + (w.calories || 0), 0);
    
    doc.setFontSize(20);
    doc.text('Workout History & Progress', 20, 20);
    
    // Summary Statistics - Page 1
    doc.setFontSize(12);
    doc.text(`Exported: ${today}`, 20, 30);
    
    let y = 45;
    doc.setFontSize(14);
    doc.text('Workout Summary', 20, y); y += 10;
    doc.setFontSize(11);
    doc.text(`Total Workouts: ${totalWorkouts}`, 25, y); y += 7;
    doc.text(`Total Duration: ${totalDuration} minutes`, 25, y); y += 7;
    doc.text(`Average Duration: ${avgDuration} minutes per workout`, 25, y); y += 7;
    doc.text(`Total Calories Burned: ${totalCalories}`, 25, y); y += 12;
    
    doc.setFontSize(14);
    doc.text('Last 7 Days Performance', 20, y); y += 10;
    doc.setFontSize(11);
    doc.text(`Workouts Last 7 Days: ${last7Days.length}`, 25, y); y += 7;
    doc.text(`Calories Burned Last 7 Days: ${last7Calories}`, 25, y); y += 12;
    
    doc.setFontSize(14);
    doc.text('Workout Breakdown by Type', 20, y); y += 10;
    doc.setFontSize(11);
    Object.entries(workoutsByType).forEach(([type, count]) => {
      doc.text(`${type}: ${count} workouts`, 25, y);
      y += 7;
    });
    
    // Page 2 - Detailed Workout Log
    doc.addPage();
    doc.setFontSize(16);
    doc.text('Detailed Workout Log', 20, 20);
    doc.setFontSize(11);
    y = 35;
    
    if (workoutLog.length === 0) {
      doc.text('No workouts logged yet', 25, y);
    } else {
      workoutLog.slice(0, 40).forEach((workout, index) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        
        const date = new Date(workout.date).toLocaleDateString();
        doc.text(`${index + 1}. ${workout.name}`, 25, y);
        y += 6;
        doc.setFontSize(9);
        
        let details = `   Date: ${date}`;
        if (workout.duration) details += ` | Duration: ${workout.duration} min`;
        if (workout.calories) details += ` | Calories: ${workout.calories}`;
        if (workout.type) details += ` | Type: ${workout.type}`;
        
        doc.text(details, 25, y);
        y += 8;
        doc.setFontSize(11);
      });
    }
    
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 285);
    
    const timestamp = new Date().toISOString().split('T')[0];
    await this.savePDFMobile(doc, `helio-workouts-${timestamp}.pdf`);
  }

  // Export food log
  async exportFoodLog() {
    const doc = new jsPDF();
    const foodLog = JSON.parse(localStorage.getItem('foodLog') || '[]');
    const today = new Date().toISOString().split('T')[0];
    
    // Get last 30 days of food logs (full history)
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    const recentFoods = foodLog.filter(f => {
      const foodDate = new Date(f.timestamp || f.date);
      return foodDate >= thirtyDaysAgo;
    }).sort((a, b) => new Date(b.timestamp || b.date) - new Date(a.timestamp || a.date));
    
    doc.setFontSize(20);
    doc.text('Complete Nutrition History', 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Period: Last 30 Days`, 20, 30);
    doc.text(`Total Meals: ${recentFoods.length}`, 20, 37);
    
    // Calculate totals for last 30 days
    let totalCalories = 0;
    let totalProtein = 0;
    let totalCarbs = 0;
    let totalFat = 0;
    
    recentFoods.forEach(food => {
      totalCalories += food.calories || 0;
      totalProtein += food.protein || 0;
      totalCarbs += food.carbs || 0;
      totalFat += food.fat || 0;
    });
    
    // Calculate daily averages
    const daysWithData = Math.max(1, recentFoods.length > 0 ? 30 : 1);
    const avgCalories = Math.round(totalCalories / daysWithData);
    const avgProtein = Math.round(totalProtein / daysWithData);
    const avgCarbs = Math.round(totalCarbs / daysWithData);
    const avgFat = Math.round(totalFat / daysWithData);
    
    doc.setFontSize(14);
    doc.text('30-Day Totals & Averages', 20, 50);
    doc.setFontSize(11);
    doc.text(`Total Calories: ${totalCalories} kcal (Avg: ${avgCalories}/day)`, 25, 58);
    doc.text(`Total Protein: ${totalProtein}g (Avg: ${avgProtein}g/day)`, 25, 65);
    doc.text(`Total Carbs: ${totalCarbs}g (Avg: ${avgCarbs}g/day)`, 25, 72);
    doc.text(`Total Fat: ${totalFat}g (Avg: ${avgFat}g/day)`, 25, 79);
    
    // Food list
    doc.setFontSize(14);
    doc.text('Recent Meals (Last 30 Days)', 20, 95);
    doc.setFontSize(10);
    
    let y = 105;
    if (recentFoods.length === 0) {
      doc.text('No foods logged in last 30 days', 25, y);
    } else {
      recentFoods.slice(0, 100).forEach((food, index) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        
        const foodDate = new Date(food.timestamp || food.date);
        const dateStr = foodDate.toLocaleDateString();
        const timeStr = foodDate.toLocaleTimeString();
        doc.text(`${index + 1}. ${food.name}`, 25, y);
        y += 5;
        doc.setFontSize(8);
        doc.text(`   ${dateStr} ${timeStr} | ${food.calories}cal | P:${food.protein}g C:${food.carbs}g F:${food.fat}g`, 25, y);
        y += 8;
        doc.setFontSize(10);
      });
    }
    
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 285);
    
    const timestamp = new Date().toISOString().split('T')[0];
    await this.savePDFMobile(doc, `helio-nutrition-${timestamp}.pdf`);
  }

  // Export full health report WITH HEALTH AVATAR, DNA, AND VITAL SIGNS
  async exportFullReport(stats) {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString();
    
    // Cover page
    doc.setFontSize(24);
    doc.text('Helio Health Report', 20, 30);
    doc.setFontSize(14);
    doc.text('Complete Wellness Summary', 20, 45);
    doc.setFontSize(12);
    doc.text(`Generated: ${today}`, 20, 55);
    doc.text(`User: ${localStorage.getItem('userName') || 'User'}`, 20, 62);
    
    // Page 2 - Activity
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Activity & Fitness', 20, 20);
    doc.setFontSize(11);
    
    let y = 35;
    doc.text(`Steps Today: ${stats.todaySteps}`, 25, y); y += 8;
    doc.text(`Goal: ${stats.goalSteps} steps`, 25, y); y += 8;
    doc.text(`Completion: ${Math.round((stats.todaySteps / stats.goalSteps) * 100)}%`, 25, y); y += 8;
    doc.text(`Active Streak: ${stats.streak} days`, 25, y); y += 8;
    doc.text(`Level: ${stats.level} (${stats.xp} XP)`, 25, y); y += 15;
    
    doc.setFontSize(14);
    doc.text('Weekly Steps', 25, y); y += 10;
    doc.setFontSize(10);
    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    stats.weeklySteps?.forEach((day, index) => {
      doc.text(`${days[index]}: ${day.steps || 0} steps`, 30, y);
      y += 7;
    });
    
    // Page 3 - Workouts & Nutrition
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Workouts & Nutrition', 20, 20);
    doc.setFontSize(14);
    y = 35;
    
    // Workout Summary
    const workoutHistory = JSON.parse(localStorage.getItem('workoutHistory') || '[]');
    const totalWorkouts = workoutHistory.length;
    const totalCaloriesBurned = workoutHistory.reduce((sum, w) => sum + (w.calories || 0), 0);
    const last7Days = workoutHistory.filter(w => {
      const workoutDate = new Date(w.date);
      const sevenDaysAgo = new Date();
      sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
      return workoutDate >= sevenDaysAgo;
    }).length;
    
    doc.text('Workout Summary', 25, y); y += 10;
    doc.setFontSize(11);
    doc.text(`Total Workouts: ${totalWorkouts}`, 30, y); y += 7;
    doc.text(`Workouts Last 7 Days: ${last7Days}`, 30, y); y += 7;
    doc.text(`Total Calories Burned: ${totalCaloriesBurned}`, 30, y); y += 15;
    
    // Nutrition & Hydration
    doc.setFontSize(14);
    doc.text('Nutrition & Hydration', 25, y); y += 10;
    doc.setFontSize(11);
    doc.text(`Water Intake Today: ${stats.waterCups} / 8 cups`, 30, y); y += 7;
    doc.text(`Meals Logged Today: ${stats.mealsLogged}`, 30, y); y += 7;
    doc.text(`Hydration Level: ${Math.round((stats.waterCups / 8) * 100)}%`, 30, y); y += 15;
    
    // Page 4 - HEALTH AVATAR DATA (NEW)
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Health Avatar & AI Analysis', 20, 20);
    doc.setFontSize(11);
    y = 35;
    
    try {
      const { default: healthAvatarService } = await import('./healthAvatarService');
      const avatarState = await healthAvatarService.getAvatarState(true);
      
      doc.setFontSize(14);
      doc.text('Current Health Status', 25, y); y += 10;
      doc.setFontSize(11);
      doc.text(`Overall Health Score: ${avatarState?.current?.score || 'N/A'}/100`, 30, y); y += 7;
      doc.text(`Health Status: ${avatarState?.current?.score >= 70 ? 'Excellent' : avatarState?.current?.score >= 50 ? 'Good' : 'Needs Improvement'}`, 30, y); y += 12;
      
      doc.setFontSize(14);
      doc.text('Score Breakdown', 25, y); y += 10;
      doc.setFontSize(10);
      
      if (avatarState?.current?.scoreBreakdown) {
        avatarState.current.scoreBreakdown.slice(0, 10).forEach((factor) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          const points = factor.points > 0 ? '+' + factor.points : factor.points;
          doc.text(`${factor.icon} ${factor.factor}: ${points} points`, 30, y);
          y += 6;
        });
      }
    } catch (err) {
      doc.text('Health Avatar data not available', 30, y);
    }
    
    // Page 5 - DNA & VITAL SIGNS (NEW)
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Genetic Analysis & Vital Signs', 20, 20);
    doc.setFontSize(11);
    y = 35;
    
    // DNA Section
    doc.setFontSize(14);
    doc.text('DNA Analysis', 25, y); y += 10;
    doc.setFontSize(11);
    
    try {
      let dnaAnalysis = null;
      try {
        dnaAnalysis = JSON.parse(localStorage.getItem('dnaAnalysis') || 'null');
      } catch (e) {
        dnaAnalysis = null;
      }
      
      if (dnaAnalysis && dnaAnalysis.traits && dnaAnalysis.traits.length > 0) {
        const highRisks = dnaAnalysis.traits.filter(t => t.risk === 'high');
        const mediumRisks = dnaAnalysis.traits.filter(t => t.risk === 'medium');
        
        doc.text(`Total Traits Analyzed: ${dnaAnalysis.traits.length}`, 30, y); y += 7;
        doc.text(`High Risk Traits: ${highRisks.length}`, 30, y); y += 7;
        doc.text(`Medium Risk Traits: ${mediumRisks.length}`, 30, y); y += 12;
        
        doc.setFontSize(10);
        doc.text('High Risk Traits:', 30, y); y += 6;
        highRisks.slice(0, 5).forEach((trait) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.text(`  • ${trait.name}: ${trait.description}`, 35, y);
          y += 6;
        });
      } else {
        doc.text('No DNA data uploaded yet', 30, y); y += 7;
      }
    } catch (err) {
      doc.text('DNA data not available', 30, y); y += 7;
    }
    
    y += 10;
    // Vital Signs Section
    doc.setFontSize(14);
    doc.text('Vital Signs & Sleep', 25, y); y += 10;
    doc.setFontSize(11);
    
    // Get sleep data
    try {
      const sleepLog = JSON.parse(localStorage.getItem('sleepLog') || '[]');
      const recentSleep = sleepLog.slice(-7);
      const avgSleep = recentSleep.length > 0 ? 
        (recentSleep.reduce((sum, s) => sum + (s.hours || 0), 0) / recentSleep.length).toFixed(1) : 
        'Not tracked';
      
      doc.text(`Average Sleep (Last 7 Days): ${avgSleep} hours`, 30, y); y += 7;
    } catch (e) {
      doc.text(`Average Sleep (Last 7 Days): Not tracked`, 30, y); y += 7;
    }
    
    doc.text(`Heart Rate: ${stats.heartRate ? stats.heartRate + ' bpm' : 'Not monitored'}`, 30, y); y += 7;
    doc.text(`Fall Detection: Active & Monitoring`, 30, y); y += 7;
    doc.text(`Emergency Features: Enabled & Ready`, 30, y); y += 12;
    
    // Page 6 - MEDICAL PROFILE & RECOMMENDATIONS (NEW)
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Medical Profile & Recommendations', 20, 20);
    doc.setFontSize(11);
    y = 35;
    
    // Medical Conditions
    doc.setFontSize(14);
    doc.text('Medical Information', 25, y); y += 10;
    doc.setFontSize(11);
    
    const userProfile = JSON.parse(localStorage.getItem('userProfile') || '{}');
    const conditions = userProfile.medicalConditions || [];
    const allergies = userProfile.allergies || [];
    
    if (conditions.length > 0) {
      doc.text(`Medical Conditions: ${conditions.join(', ')}`, 30, y);
    } else {
      doc.text(`Medical Conditions: None reported`, 30, y);
    }
    y += 10;
    
    if (allergies.length > 0) {
      doc.text(`Allergies: ${allergies.join(', ')}`, 30, y);
    } else {
      doc.text(`Allergies: None reported`, 30, y);
    }
    y += 10;
    
    // BMI Calculation
    const height = userProfile.height || 0;
    const weight = userProfile.weight || 0;
    const bmi = height && weight ? (weight / ((height/100) * (height/100))).toFixed(1) : 'Not calculated';
    doc.text(`BMI: ${bmi}`, 30, y); y += 10;
    
    // Wellness Summary
    doc.setFontSize(14);
    doc.text('Overall Wellness Analysis', 25, y); y += 10;
    doc.setFontSize(11);
    doc.text(`Overall Wellness Score: ${stats.wellnessScore}/100`, 25, y); y += 10;
    doc.setFontSize(10);
    doc.text('Score calculated from:', 25, y); y += 7;
    doc.text('• Daily activity and steps', 30, y); y += 6;
    doc.text('• Sleep quality and duration', 30, y); y += 6;
    doc.text('• Nutrition and hydration', 30, y); y += 6;
    doc.text('• Workout frequency and intensity', 30, y); y += 6;
    doc.text('• Genetic risk factors', 30, y); y += 6;
    doc.text('• Consistency and streaks', 30, y); y += 6;
    doc.text('• Emergency preparedness', 30, y);
    
    // Footer on last page
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 280);
    doc.text('This report is for informational purposes only and not medical advice. Always consult healthcare professionals for medical decisions.', 20, 285);
    
    const timestamp = new Date().toISOString().split('T')[0];
    await this.savePDFMobile(doc, `helio-full-report-${timestamp}.pdf`);
  }

  // Export workout history as CSV
  async exportWorkoutHistoryCSV() {
    try {
      const workoutHistory = JSON.parse(localStorage.getItem('workoutHistory') || '[]');
      const today = new Date().toLocaleDateString().replace(/\//g, '-');
      
      if (workoutHistory.length === 0) {
        alert('No workout data to export');
        return;
      }
      
      // CSV Header
      let csvContent = 'Date,Workout Name,Type,Duration (min),Calories,Sets,Reps,Notes\n';
      
      // CSV Rows
      workoutHistory.forEach(workout => {
        const date = new Date(workout.date).toLocaleDateString();
        const name = (workout.name || 'Workout').replace(/,/g, ';'); // Escape commas
        const type = workout.type || 'General';
        const duration = workout.duration || 'N/A';
        const calories = workout.calories || 0;
        const sets = workout.sets || 'N/A';
        const reps = workout.reps || 'N/A';
        const notes = (workout.notes || '').replace(/,/g, ';').replace(/\n/g, ' ');
        
        csvContent += `${date},${name},${type},${duration},${calories},${sets},${reps},${notes}\n`;
      });
      
      if (Capacitor.isNativePlatform()) {
        // Save CSV to mobile
        const csvBase64 = btoa(unescape(encodeURIComponent(csvContent)));
        const result = await Filesystem.writeFile({
          path: `helio-workouts-${today}.csv`,
          data: csvBase64,
          directory: Directory.Cache
        });
        
        await Share.share({
          title: 'Helio Workout History',
          text: 'Your workout history CSV',
          url: result.uri,
          dialogTitle: 'Share workout data'
        });
        
        alert('✅ CSV ready to share!');
      } else {
        // Browser download
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `helio-workouts-${today}.csv`;
        link.click();
      }
    } catch (error) {
      console.error('❌ CSV export error:', error);
      alert('Failed to export CSV: ' + error.message);
    }
  }

  // Export food log as CSV
  async exportFoodLogCSV() {
    try {
      const foodLog = JSON.parse(localStorage.getItem('foodLog') || '[]');
      const today = new Date().toLocaleDateString().replace(/\//g, '-');
      
      // Get last 30 days
      const thirtyDaysAgo = new Date();
      thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
      const recentFoods = foodLog.filter(f => {
        const foodDate = new Date(f.timestamp || f.date);
        return foodDate >= thirtyDaysAgo;
      }).sort((a, b) => new Date(b.timestamp || b.date) - new Date(a.timestamp || a.date));
      
      if (recentFoods.length === 0) {
        alert('No food data to export');
        return;
      }
      
      // CSV Header
      let csvContent = 'Date,Time,Food Name,Calories,Protein (g),Carbs (g),Fat (g),Meal Type\n';
      
      // CSV Rows
      recentFoods.forEach(food => {
        const foodDate = new Date(food.timestamp || food.date);
        const date = foodDate.toLocaleDateString();
        const time = foodDate.toLocaleTimeString();
        const name = (food.name || 'Food').replace(/,/g, ';');
        const calories = food.calories || 0;
        const protein = food.protein || 0;
        const carbs = food.carbs || 0;
        const fat = food.fat || 0;
        const mealType = food.mealType || 'Snack';
        
        csvContent += `${date},${time},${name},${calories},${protein},${carbs},${fat},${mealType}\n`;
      });
      
      if (Capacitor.isNativePlatform()) {
        // Save CSV to mobile
        const csvBase64 = btoa(unescape(encodeURIComponent(csvContent)));
        const result = await Filesystem.writeFile({
          path: `helio-nutrition-${today}.csv`,
          data: csvBase64,
          directory: Directory.Cache
        });
        
        await Share.share({
          title: 'Helio Nutrition History',
          text: 'Your nutrition history CSV',
          url: result.uri,
          dialogTitle: 'Share nutrition data'
        });
        
        alert('✅ CSV ready to share!');
      } else {
        // Browser download
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `helio-nutrition-${today}.csv`;
        link.click();
      }
    } catch (error) {
      console.error('❌ CSV export error:', error);
      alert('Failed to export CSV: ' + error.message);
    }
  }
}

export default new PDFExportService();



