// PDF Export Service - Export health data and reports
import { jsPDF } from 'jspdf';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { Capacitor } from '@capacitor/core';

class PDFExportService {
  // Helper to save PDF on mobile devices
  async savePDFMobile(doc, filename) {
    try {
      if (Capacitor.isNativePlatform()) {
        // Get PDF as base64
        const pdfBase64 = doc.output('datauristring').split(',')[1];
        
        // Save to device
        const result = await Filesystem.writeFile({
          path: filename,
          data: pdfBase64,
          directory: Directory.Documents
        });
        
        if(import.meta.env.DEV)console.log('✅ PDF saved to:', result.uri);
        
        // Share the PDF
        await Share.share({
          title: 'Helio Health Report',
          text: 'Your health report from Helio',
          url: result.uri,
          dialogTitle: 'Share your report'
        });
        
        alert('✅ PDF saved and ready to share!');
      } else {
        // Browser - use normal download
        doc.save(filename);
      }
    } catch (error) {
      if(import.meta.env.DEV)console.error('❌ PDF save error:', error);
      alert('Failed to save PDF: ' + error.message);
    }
  }

  // Export daily stats summary
  async exportDailyStats(stats) {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString();
    
    // Title
    doc.setFontSize(20);
    doc.text('Helio Daily Health Report', 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Date: ${today}`, 20, 30);
    
    // Stats
    doc.setFontSize(14);
    doc.text('Daily Activity Summary', 20, 45);
    
    doc.setFontSize(11);
    let y = 55;
    doc.text(`Steps: ${stats.todaySteps} / ${stats.goalSteps}`, 25, y);
    y += 8;
    doc.text(`Water: ${stats.waterCups} / 8 cups`, 25, y);
    y += 8;
    doc.text(`Meals Logged: ${stats.mealsLogged}`, 25, y);
    y += 8;
    doc.text(`Streak: ${stats.streak} days`, 25, y);
    y += 8;
    doc.text(`Level: ${stats.level} | XP: ${stats.xp}`, 25, y);
    y += 8;
    doc.text(`Wellness Score: ${stats.wellnessScore}/100`, 25, y);
    
    // Weekly Steps Chart
    y += 15;
    doc.setFontSize(14);
    doc.text('Weekly Steps Summary', 20, y);
    y += 10;
    doc.setFontSize(10);
    
    const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    stats.weeklySteps?.forEach((day, index) => {
      doc.text(`${days[index]}: ${day.steps || 0} steps`, 25, y);
      y += 7;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 280);
    doc.text('This report is for informational purposes only', 20, 285);
    
    // Save
    await this.savePDFMobile(doc, `helio-daily-report-${today.replace(/\//g, '-')}.pdf`);
  }

  // Export workout history
  async exportWorkoutHistory() {
    const doc = new jsPDF();
    const workoutLog = JSON.parse(localStorage.getItem('workoutLog') || '[]');
    const today = new Date().toLocaleDateString();
    
    doc.setFontSize(20);
    doc.text('Workout History', 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Total Workouts: ${workoutLog.length}`, 20, 30);
    doc.text(`Exported: ${today}`, 20, 37);
    
    doc.setFontSize(11);
    let y = 50;
    
    if (workoutLog.length === 0) {
      doc.text('No workouts logged yet', 25, y);
    } else {
      workoutLog.slice(0, 30).forEach((workout, index) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        
        const date = new Date(workout.date).toLocaleDateString();
        doc.text(`${index + 1}. ${workout.name}`, 25, y);
        y += 6;
        doc.setFontSize(9);
        doc.text(`   Date: ${date} | Duration: ${workout.duration || 'N/A'} | Calories: ${workout.calories || 'N/A'}`, 25, y);
        y += 8;
        doc.setFontSize(11);
      });
    }
    
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 285);
    
    await this.savePDFMobile(doc, `helio-workout-history-${today.replace(/\//g, '-')}.pdf`);
  }

  // Export food log
  async exportFoodLog() {
    const doc = new jsPDF();
    const foodLog = JSON.parse(localStorage.getItem('foodLog') || '[]');
    const today = new Date().toISOString().split('T')[0];
    const todaysFoods = foodLog.filter(f => 
      f.date === today || new Date(f.timestamp).toISOString().split('T')[0] === today
    );
    
    doc.setFontSize(20);
    doc.text('Daily Nutrition Log', 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 30);
    doc.text(`Total Meals: ${todaysFoods.length}`, 20, 37);
    
    // Calculate totals
    let totalCalories = 0;
    let totalProtein = 0;
    let totalCarbs = 0;
    let totalFat = 0;
    
    todaysFoods.forEach(food => {
      totalCalories += food.calories || 0;
      totalProtein += food.protein || 0;
      totalCarbs += food.carbs || 0;
      totalFat += food.fat || 0;
    });
    
    doc.setFontSize(14);
    doc.text('Daily Totals', 20, 50);
    doc.setFontSize(11);
    doc.text(`Calories: ${totalCalories} kcal`, 25, 58);
    doc.text(`Protein: ${totalProtein}g`, 25, 65);
    doc.text(`Carbs: ${totalCarbs}g`, 25, 72);
    doc.text(`Fat: ${totalFat}g`, 25, 79);
    
    // Food list
    doc.setFontSize(14);
    doc.text('Foods Consumed', 20, 95);
    doc.setFontSize(10);
    
    let y = 105;
    if (todaysFoods.length === 0) {
      doc.text('No foods logged today', 25, y);
    } else {
      todaysFoods.forEach((food, index) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        
        const time = new Date(food.timestamp).toLocaleTimeString();
        doc.text(`${index + 1}. ${food.name}`, 25, y);
        y += 5;
        doc.setFontSize(8);
        doc.text(`   ${time} | ${food.calories}cal | P:${food.protein}g C:${food.carbs}g F:${food.fat}g`, 25, y);
        y += 8;
        doc.setFontSize(10);
      });
    }
    
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 285);
    
    await this.savePDFMobile(doc, `helio-nutrition-${today}.pdf`);
  }

  // Export full health report
  async exportFullReport(stats) {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString();
    
    // Cover page
    doc.setFontSize(24);
    doc.text('Helio Health Report', 20, 30);
    doc.setFontSize(14);
    doc.text('Complete Wellness Summary', 20, 45);
    doc.setFontSize(12);
    doc.text(`Generated: ${today}`, 20, 55);
    doc.text(`User: ${localStorage.getItem('userName') || 'User'}`, 20, 62);
    
    // Page 2 - Activity
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Activity & Fitness', 20, 20);
    doc.setFontSize(11);
    
    let y = 35;
    doc.text(`Steps Today: ${stats.todaySteps}`, 25, y); y += 8;
    doc.text(`Goal: ${stats.goalSteps} steps`, 25, y); y += 8;
    doc.text(`Completion: ${Math.round((stats.todaySteps / stats.goalSteps) * 100)}%`, 25, y); y += 8;
    doc.text(`Active Streak: ${stats.streak} days`, 25, y); y += 8;
    doc.text(`Level: ${stats.level} (${stats.xp} XP)`, 25, y); y += 15;
    
    doc.setFontSize(14);
    doc.text('Weekly Steps', 25, y); y += 10;
    doc.setFontSize(10);
    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    stats.weeklySteps?.forEach((day, index) => {
      doc.text(`${days[index]}: ${day.steps || 0} steps`, 30, y);
      y += 7;
    });
    
    // Page 3 - Nutrition
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Nutrition & Hydration', 20, 20);
    doc.setFontSize(11);
    y = 35;
    
    doc.text(`Water Intake: ${stats.waterCups} / 8 cups`, 25, y); y += 8;
    doc.text(`Meals Logged: ${stats.mealsLogged}`, 25, y); y += 8;
    doc.text(`Hydration: ${Math.round((stats.waterCups / 8) * 100)}%`, 25, y); y += 15;
    
    // Page 4 - Wellness Score
    doc.addPage();
    doc.setFontSize(18);
    doc.text('Wellness Analysis', 20, 20);
    doc.setFontSize(11);
    y = 35;
    
    doc.text(`Overall Wellness Score: ${stats.wellnessScore}/100`, 25, y); y += 10;
    doc.setFontSize(10);
    doc.text('This score is calculated based on:', 25, y); y += 7;
    doc.text('• Daily activity and steps', 30, y); y += 6;
    doc.text('• Nutrition and hydration', 30, y); y += 6;
    doc.text('• Sleep quality', 30, y); y += 6;
    doc.text('• Consistency and streaks', 30, y); y += 6;
    doc.text('• Mental wellness activities', 30, y);
    
    // Footer on last page
    doc.setFontSize(8);
    doc.text('Generated by Helio/WellnessAI', 20, 280);
    doc.text('This report is for informational purposes only and not medical advice', 20, 285);
    
    await this.savePDFMobile(doc, `helio-full-report-${today.replace(/\//g, '-')}.pdf`);
  }
}

export default new PDFExportService();



