// AI Workout Generator - Beta Feature
// Generates personalized workout plans using Gemini AI
import { useState } from 'react';
import { showToast } from './Toast';
import BetaFeatureWrapper from './BetaFeatureWrapper';
import dataService from '../services/dataService'; // 🎯 SINGLE SOURCE OF TRUTH
import authService from '../services/authService';
import './AIWorkoutGenerator.css';

export default function AIWorkoutGenerator() {
  const [loading, setLoading] = useState(false);
  const [workoutPlan, setWorkoutPlan] = useState(null);
  const [error, setError] = useState(null);
  
  // User preferences
  const [fitnessLevel, setFitnessLevel] = useState('intermediate');
  const [goal, setGoal] = useState('strength');
  const [duration, setDuration] = useState('30');
  const [equipment, setEquipment] = useState('bodyweight');

  const generateWorkout = async () => {
    setLoading(true);
    setError(null);
    setWorkoutPlan(null);

    try {
      const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error('Gemini API key not configured');
      }

      const prompt = `You are a professional fitness coach. Generate a detailed ${duration}-minute workout plan with the following requirements:

Fitness Level: ${fitnessLevel}
Primary Goal: ${goal}
Available Equipment: ${equipment}

Provide a structured workout plan with:
1. Warm-up (5 minutes)
2. Main workout exercises (with reps/sets/duration)
3. Cool-down (5 minutes)

Format as JSON with this structure:
{
  "title": "workout name",
  "warmup": ["exercise 1", "exercise 2"],
  "exercises": [
    {
      "name": "exercise name",
      "sets": 3,
      "reps": "12-15",
      "rest": "60 seconds",
      "notes": "form tips"
    }
  ],
  "cooldown": ["stretch 1", "stretch 2"]
}

Make it challenging but achievable for ${fitnessLevel} level.`;

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              parts: [{ text: prompt }]
            }],
            generationConfig: {
              temperature: 0.8,
              maxOutputTokens: 2048
            }
          }),
          signal: AbortSignal.timeout(30000)
        }
      );

      if (!response.ok) {
        throw new Error('Failed to generate workout');
      }

      const data = await response.json();
      const text = data.candidates[0]?.content?.parts[0]?.text;
      
      if (!text) {
        throw new Error('No response from AI');
      }

      // Parse JSON from response (remove markdown code blocks if present)
      const jsonMatch = text.match(/```json\n?([\s\S]*?)\n?```/) || text.match(/{[\s\S]*}/);
      if (jsonMatch) {
        const plan = JSON.parse(jsonMatch[1] || jsonMatch[0]);
        setWorkoutPlan(plan);
      } else {
        throw new Error('Invalid response format');
      }

    } catch (err) {
      console.error('AI Workout Generator error:', err);
      setError(err.message || 'Failed to generate workout');
    } finally {
      setLoading(false);
    }
  };

  const saveWorkout = async () => {
    if (!workoutPlan) return;

    try {
      // 🔥 FIX: Read localStorage FIRST for instant data (Firestore is stale)
      let workoutHistory = [];
      try {
        workoutHistory = JSON.parse(localStorage.getItem('workoutHistory') || '[]');
      } catch (e) {
        console.error('Error loading workout history:', e);
        workoutHistory = [];
      }
      
      const workout = {
        id: Date.now(),
        name: workoutPlan.title,
        type: goal,
        duration: parseInt(duration),
        exercises: workoutPlan.exercises.length,
        calories: Math.round(parseInt(duration) * 8), // Rough estimate
        date: new Date().toISOString(),
        aiGenerated: true,
        plan: workoutPlan
      };

      workoutHistory.unshift(workout);
      
      // 🔥 FIX: Save via dataService (handles Preferences + localStorage + Firestore)
      const userId = authService.getCurrentUser()?.uid;
      await dataService.save('workoutHistory', workoutHistory, userId);
      localStorage.setItem('workoutHistory', JSON.stringify(workoutHistory));

      showToast('Workout saved! Go to Workouts tab to start training.', 'success');
    } catch (err) {
      console.error('Failed to save workout:', err);
      showToast('Failed to save workout', 'error');
    }
  };

  return (
    <BetaFeatureWrapper featureName="AI Workout Generator">
      <div className="ai-workout-generator">
        <div className="generator-intro">
          <h2>🤖 AI Workout Generator</h2>
          <p>Get personalized workout plans generated by AI based on your fitness level, goals, and available equipment.</p>
        </div>

        <div className="generator-form">
          <div className="form-section">
            <label>Fitness Level</label>
            <select value={fitnessLevel} onChange={(e) => setFitnessLevel(e.target.value)}>
              <option value="beginner">🌱 Beginner</option>
              <option value="intermediate">💪 Intermediate</option>
              <option value="advanced">🏆 Advanced</option>
              <option value="expert">⚡ Expert</option>
            </select>
          </div>

          <div className="form-section">
            <label>Primary Goal</label>
            <select value={goal} onChange={(e) => setGoal(e.target.value)}>
              <option value="strength">💪 Strength Building</option>
              <option value="cardio">🏃 Cardio Endurance</option>
              <option value="flexibility">🧘 Flexibility</option>
              <option value="weight_loss">🔥 Weight Loss</option>
              <option value="muscle_gain">💎 Muscle Gain</option>
              <option value="hiit">⚡ HIIT Training</option>
            </select>
          </div>

          <div className="form-section">
            <label>Workout Duration</label>
            <select value={duration} onChange={(e) => setDuration(e.target.value)}>
              <option value="15">⏱️ 15 minutes</option>
              <option value="30">⏱️ 30 minutes</option>
              <option value="45">⏱️ 45 minutes</option>
              <option value="60">⏱️ 60 minutes</option>
            </select>
          </div>

          <div className="form-section">
            <label>Available Equipment</label>
            <select value={equipment} onChange={(e) => setEquipment(e.target.value)}>
              <option value="bodyweight">🤸 Bodyweight Only</option>
              <option value="dumbbells">🏋️ Dumbbells</option>
              <option value="full_gym">🏢 Full Gym Access</option>
              <option value="resistance_bands">🎗️ Resistance Bands</option>
              <option value="home_equipment">🏠 Basic Home Equipment</option>
            </select>
          </div>

          <button 
            className="generate-btn"
            onClick={generateWorkout}
            disabled={loading}
          >
            {loading ? '⏳ Generating...' : '🚀 Generate Workout'}
          </button>
        </div>

        {error && (
          <div className="error-message">
            ❌ {error}
          </div>
        )}

        {workoutPlan && (
          <div className="workout-plan">
            <h3>{workoutPlan.title}</h3>
            
            <div className="plan-section">
              <h4>🔥 Warm-up (5 min)</h4>
              <ul>
                {workoutPlan.warmup?.map((exercise, idx) => (
                  <li key={idx}>{exercise}</li>
                ))}
              </ul>
            </div>

            <div className="plan-section">
              <h4>💪 Main Workout</h4>
              {workoutPlan.exercises?.map((exercise, idx) => (
                <div key={idx} className="exercise-card">
                  <div className="exercise-number">{idx + 1}</div>
                  <div className="exercise-details">
                    <h5>{exercise.name}</h5>
                    <div className="exercise-specs">
                      <span>📊 {exercise.sets} sets</span>
                      <span>🔢 {exercise.reps} reps</span>
                      <span>⏸️ {exercise.rest} rest</span>
                    </div>
                    {exercise.notes && (
                      <p className="exercise-notes">💡 {exercise.notes}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div className="plan-section">
              <h4>🧘 Cool-down (5 min)</h4>
              <ul>
                {workoutPlan.cooldown?.map((stretch, idx) => (
                  <li key={idx}>{stretch}</li>
                ))}
              </ul>
            </div>

            <button className="save-workout-btn" onClick={saveWorkout}>
              💾 Save to My Workouts
            </button>
          </div>
        )}
      </div>
    </BetaFeatureWrapper>
  );
}
